// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC_Y7q5MmHgjMAet7eOFhXpIvWLeQ_3DE',
    appId: '1:257992414422:web:94048e59069c68dca26577',
    messagingSenderId: '257992414422',
    projectId: 'fypproj-721cd',
    authDomain: 'fypproj-721cd.firebaseapp.com',
    storageBucket: 'fypproj-721cd.appspot.com',
    measurementId: 'G-J2MVC67FZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa1al3QnQB5eh3ZACryMXoUAE3c08Ysnw',
    appId: '1:257992414422:android:44a01a14d789d80ea26577',
    messagingSenderId: '257992414422',
    projectId: 'fypproj-721cd',
    storageBucket: 'fypproj-721cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3Uj7sbSIzQOfmrzfg4LGRrx41f6DIhI',
    appId: '1:257992414422:ios:91934a3b8ccc955ca26577',
    messagingSenderId: '257992414422',
    projectId: 'fypproj-721cd',
    storageBucket: 'fypproj-721cd.appspot.com',
    iosBundleId: 'com.example.fypProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3Uj7sbSIzQOfmrzfg4LGRrx41f6DIhI',
    appId: '1:257992414422:ios:91934a3b8ccc955ca26577',
    messagingSenderId: '257992414422',
    projectId: 'fypproj-721cd',
    storageBucket: 'fypproj-721cd.appspot.com',
    iosBundleId: 'com.example.fypProj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC_Y7q5MmHgjMAet7eOFhXpIvWLeQ_3DE',
    appId: '1:257992414422:web:59a44cc511319222a26577',
    messagingSenderId: '257992414422',
    projectId: 'fypproj-721cd',
    authDomain: 'fypproj-721cd.firebaseapp.com',
    storageBucket: 'fypproj-721cd.appspot.com',
    measurementId: 'G-9PLY7EWXFD',
  );
}
